use_frameworks!

platform :ios, '10.0'

target 'AlipayVerify_Example' do
  pod 'AlipayVerify', :path => '../'

  target 'AlipayVerify_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
